### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by xpavciak** [xpavciak/STUkaris#1]
# TO DO 
- [x] vytvorenie repo
- [ ] instalacia android studia ( robert )
- [ ] vytvorenie projektu skusenie hello world ( robert ) 
- [ ] rozhodnutie medzi skenovanim obrazka a pristupu cez URL adresu... 
- [ ] studium
- [ ] spravit navrh
- [ ] dva tyzdne, najblizsie stretko v auguste, komunikujeme cez chat
## DONE
